# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x19\n\x08GetReply\x12\r\n\x05value\x18\x04 \x01(\x0c\"\n\n\x08SetReply2I\n\x05Store\x12\x1f\n\x03Get\x12\x0b.GetRequest\x1a\t.GetReply\"\x00\x12\x1f\n\x03Set\x12\x0b.SetRequest\x1a\t.SetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=15
  _globals['_GETREQUEST']._serialized_end=40
  _globals['_SETREQUEST']._serialized_start=42
  _globals['_SETREQUEST']._serialized_end=82
  _globals['_GETREPLY']._serialized_start=84
  _globals['_GETREPLY']._serialized_end=109
  _globals['_SETREPLY']._serialized_start=111
  _globals['_SETREPLY']._serialized_end=121
  _globals['_STORE']._serialized_start=123
  _globals['_STORE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
